export const PRODUCTS = [
  {
    id: 1,
    category: "CAMISAS",
    name: "Camisa Oficial I 2025",
    description: "A camisa I da temporada 2025 traz o tradicional manto rubro-negro em tecido leve",
    price: "R$ 349,90",
    image: "/product-1.jpg",
    badge: null,
  },
  {
    id: 2,
    category: "CAMISAS",
    name: "Camisa Oficial II 2025",
    description: "A camisa II 2025 é o uniforme alternativo da temporada, em base clara com detalhes em",
    price: "R$ 349,90",
    image: "/product-2.jpg",
    badge: null,
  },
  {
    id: 3,
    category: "CAMISAS",
    name: "Camisa Goleiro 2025",
    description: "Modelo oficial usado pelos goleiros da equipe principal. Mangas longas com reforço nos",
    price: "R$ 379,90",
    image: "/product-3.jpg",
    badge: null,
  },
  {
    id: 4,
    category: "CAMISAS",
    name: "Camisa Retrô 1981",
    description: "Réplica oficial da camisa campeã mundial de 1981, com gola V e listras clássicas. Para",
    price: "R$ 299,90",
    image: "/product-4.jpg",
    badge: "Edição",
  },
  {
    id: 5,
    category: "AGASALHOS",
    name: "Agasalho Treino Rubro-Negro",
    description: "Conjunto de treino oficial, com tecido térmico, bolsos com zíper e detalhes",
    price: "R$ 499,90",
    image: "/product-1.jpg",
    badge: "Top",
  },
  {
    id: 6,
    category: "AGASALHOS",
    name: "Jaqueta Hino",
    description: "Edição limitada da jaqueta hino, com bordado especial e numeração serializada. Apenas",
    price: "R$ 629,90",
    image: "/product-2.jpg",
    badge: "Limitado",
  },
  {
    id: 7,
    category: "AGASALHOS",
    name: "Moletom Nação",
    description: "Moletom canguru em algodão pesado, com estampa exclusiva da nação. Conforto",
    price: "R$ 389,90",
    image: "/product-3.jpg",
    badge: null,
  },
  {
    id: 8,
    category: "SHORTS",
    name: "Short Oficial Jogo",
    description: "Short usado pelos jogadores em campo, leve e com tecnologia dry-fit. Disponível em todos",
    price: "R$ 199,90",
    image: "/product-4.jpg",
    badge: "Promo",
  },
  {
    id: 9,
    category: "CAMISAS",
    name: "Camisa Oficial I 2025",
    description: "A camisa I da temporada 2025 traz o tradicional manto rubro-negro em tecido leve",
    price: "R$ 349,90",
    image: "/product-1.jpg",
    badge: null,
  },
  {
    id: 10,
    category: "CAMISAS",
    name: "Camisa Oficial II 2025",
    description: "A camisa II 2025 é o uniforme alternativo da temporada, em base clara com detalhes em",
    price: "R$ 349,90",
    image: "/product-2.jpg",
    badge: null,
  },
  {
    id: 11,
    category: "CAMISAS",
    name: "Camisa Goleiro 2025",
    description: "Modelo oficial usado pelos goleiros da equipe principal. Mangas longas com reforço nos",
    price: "R$ 379,90",
    image: "/product-3.jpg",
    badge: null,
  },
  {
    id: 12,
    category: "CAMISAS",
    name: "Camisa Retrô 1981",
    description: "Réplica oficial da camisa campeã mundial de 1981, com gola V e listras clássicas. Para",
    price: "R$ 299,90",
    image: "/product-4.jpg",
    badge: "Edição",
  },
];
